# Generated by Django 5.2.6 on 2026-01-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='used',
            field=models.IntegerField(default=0),
        ),
    ]
