# Generated by Django 5.2.6 on 2025-10-01 10:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='counter',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
