# Generated by Django 5.2.6 on 2025-10-04 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_alter_counter_created_at_alter_counter_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
