# Generated by Django 5.2.6 on 2026-01-08 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('counter', '0003_alter_counter_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counters', to='accounts.profile'),
        ),
    ]
